FROM python:3.14

RUN pip install poetry

COPY ./src/api /app/src/api
COPY ./pyproject.toml ./poetry.lock ./alembic.ini /app
COPY ./alembic /app/alembic

WORKDIR /app

RUN poetry config virtualenvs.create false
RUN poetry install --only main --no-root

CMD ["python3", "-m", "src.api"]