"""initial

Revision ID: 434114147fa3
Revises: 
Create Date: 2026-06-01 18:21:56.747811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '434114147fa3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expressions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_expression', sa.String(), nullable=False, unique=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text("timezone('utc', now())")),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expressions_id'), 'expressions', ['id'], unique=False)
    op.create_index(op.f('ix_expressions_raw_expression'), 'expressions', ['raw_expression'], unique=True)
    op.create_table('answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expression_id', sa.Integer(), nullable=False),
    sa.Column('result', sa.String(), nullable=False),
    sa.Column('votes_count', sa.Integer(), nullable=False, server_default=sa.text('1')),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text("timezone('utc', now())")),
    sa.ForeignKeyConstraint(['expression_id'], ['expressions.id'], ondelete='CASCADE'),
    sa.UniqueConstraint('expression_id', 'result', name='uix_expression_result'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answers_id'), 'answers', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_answers_id'), table_name='answers')
    op.drop_table('answers')
    op.drop_index(op.f('ix_expressions_raw_expression'), table_name='expressions')
    op.drop_index(op.f('ix_expressions_id'), table_name='expressions')
    op.drop_table('expressions')
    # ### end Alembic commands ###
